### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by seamus-sc** [storybookjs/addon-styling-webpack#22]
### Describe the bug

When trying to install Tailwind/Postcss on my existing Storybook 7.6.17 project, adding the '@storybook/addon-styling-webpack' add on causes storybook to crash with message: 

**Error: Cannot find module 'storybook/internal/node-logger'**

### Steps to reproduce the behavior

1. Start with an existing 7.6.17 project with React/Webpack5
2. `npx storybook@7.6.17 add @storybook/addon-styling-webpack`
3. Y to install missing dependencies (style-loader, css-loader, postcss-loader)
4. `npm run storybook`
5. Error:
```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/@storybook/addon-styling-webpack/dist/preset.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module 'storybook/internal/node-logger'
Require stack:
- ./node_modules/@storybook/addon-styling-webpack/node_modules/@storybook/node-logger/shim.js
- ./node_modules/@storybook/addon-styling-webpack/dist/preset.js
- ./node_modules/@storybook/core-common/dist/index.js
- ./node_modules/@storybook/telemetry/dist/index.js
- ./node_modules/@storybook/cli/dist/generate.js
- ./node_modules/@storybook/cli/bin/index.js
- ./node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._resolveFilename (./node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (./node_modules/@storybook/addon-styling-webpack/node_modules/@storybook/node-logger/shim.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (./node_modules/esbuild-register/dist/node.js:4838:24)
    at loadPreset (./node_modules/@storybook/core-common/dist/index.js:15:82)
    at loadPreset (./node_modules/@storybook/core-common/dist/index.js:15:82)
    at async Promise.all (index 1)
    at async loadPresets (./node_modules/@storybook/core-common/dist/index.js:15:505)
    at async getPresets (./node_modules/@storybook/core-common/dist/index.js:15:1525)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:119:1696)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:65:3948)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:514:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:529:225)
    ```
    6. Removing '@storybook/addon-styling-webpack' from `addons` returns storybook to a working state, though without postcss support still. 
    

### Expected behavior

Storybook should run as before, adding the plugin. 

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - OS: Mac OS 13.6.7
 - Node.js version: 20.15.0
 - NPM version: 10.7.0
 - Browser (if applicable): NA
 - Browser version (if applicable): NA
 - Device (if applicable): NA

### Additional context

Looking at storybook core, it looks like they may have moved the node-logger about 3 weeks ago? Not sure if that effects the dist build or if it was just in src. Not sure if this is related, but here's the commit https://github.com/storybookjs/storybook/commit/8505d86feeecd13a8473fa1372cf37500519d136

**Comment by ogdakke** [comment]
Same issue here, on  storybook@7.1.1 and addon 1.0.0.
Any way to circumvent this issue for the time being?

**Comment by dhruvgarg02** [comment]
I am also having the same issue with storybook@7.6.17

**Comment by timhecker** [comment]
Same issue here, on storybook@7.6.20, addon 1.0.0 and angular framework.

**Comment by thanhtran0302** [comment]
Same problem, anyone has solution ? 🙏

**Comment by kanevnik** [comment]
For anyone still stuck, the problem is with the "addon-styling-webpack" version. Storybook@7.* do not work with version 1.0.0 or 1.0.1 ( don't ask me why no clue). You have to manually go to package json and downgrade to 0.0.6 or 0.0.5 in order to work.

**Comment by ndelangen** [comment]
Hi,

Thanks for the report, and thanks to everyone who shared workarounds in the thread.

**What was going wrong**

This was a **version mismatch**, not a generic Storybook preset bug.

The reports here used **Storybook 7.6.x** (or 7.1.x) and installed `@storybook/addon-styling-webpack` **1.0.x** via `storybook add`. That addon version expects Storybook 8+ internal APIs (`storybook/internal/node-logger`), which do not exist in Storybook 7's package layout. Hence:

```
Error: Cannot find module 'storybook/internal/node-logger'
```

Workarounds that worked in this thread:

- Upgrade Storybook to 8.x or later (e.g. 8.2.9+)
- Or pin `@storybook/addon-styling-webpack` to **0.0.6** / **0.0.5** if you must stay on Storybook 7

**What changed**

Storybook 8+ consolidated packages like `@storybook/node-logger` into the core `storybook` package under `storybook/internal/*`. Storybook 10's ESM-only distribution ([#31787](https://github.com/storybookjs/storybook/issues/31787)) is the current baseline. Current releases of this addon target those versions.

**Closing**

We're closing this issue. The original report is about installing a **1.x addon on Storybook 7.6**, which is not a supported combination.

I have not personally verified `@storybook/addon-styling-webpack` on Storybook 10.5+ at this time. If you're on **matching** Storybook and addon versions (10.5+ with a current addon release) and still hit this error, please open a new issue with both version numbers and your `.storybook/main.js`.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).
